import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { site } from "@/lib/config";

export const metadata: Metadata = {
  title: "About",
  description:
    "Learn about Infinite Slop: the never-ending AI live stream, its origins with Pieter Levels, the fal.ai Max model, and how chat drives the content.",
  alternates: {
    canonical: "/about",
  },
};

export default function AboutPage() {
  return (
    <>
      <Header />
      <main className="flex-1 px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          <h1 className="text-4xl font-semibold tracking-tight text-zinc-900 sm:text-5xl">
            About Infinite Slop
          </h1>
          <p className="mt-6 text-lg leading-8 text-zinc-700">
            Infinite Slop is an experiment in endless, audience-driven media. It
            is a live stream where every video clip is generated by AI and every
            chat message helps decide what happens next. The project was built
            by{" "}
            <a
              href={site.authorUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-[#C5156B] underline hover:text-zinc-900"
            >
              {site.author}
            </a>
            , who shared the full story on{" "}
            <a
              href={site.originPost}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-[#C5156B] underline hover:text-zinc-900"
            >
              {site.originPostLabel}
            </a>
            .
          </p>

          <section className="mt-12">
            <h2 className="text-2xl font-semibold text-zinc-900">Where the idea came from</h2>
            <p className="mt-4 leading-7 text-zinc-700">
              The concept of an AI-generated live broadcast was first explored by
              streamers{" "}
              <a
                href="https://x.com/marcantoinefon"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-[#C5156B] underline hover:text-zinc-900"
              >
                marcantoinefon
              </a>{" "}
              and{" "}
              <a
                href="https://x.com/rehan_shei"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-[#C5156B] underline hover:text-zinc-900"
              >
                rehan_shei
              </a>
              . Their streams showed that a video model could be looped into a
              continuous broadcast if the audience kept feeding it ideas.
              Pieter Levels took that seed, added a polished interface, and
              launched it as a public experience anyone can drop into.
            </p>
            <p className="mt-4 leading-7 text-zinc-700">
              In his announcement, Levels described Infinite Slop as "an
              infinite and interactive AI generated live stream of slop that
              goes on forever and ever." The playful name matches the surreal
              feel of watching an AI try to maintain a storyline across dozens
              of unrelated prompts.
            </p>
          </section>

          <section className="mt-12">
            <h2 className="text-2xl font-semibold text-zinc-900">The AI engine</h2>
            <p className="mt-4 leading-7 text-zinc-700">
              Running a never-ending AI video stream is expensive and
              technically demanding. The system has to generate clips quickly
              enough that the viewer never reaches the end of the buffer. That
              is where{" "}
              <a
                href={site.sponsorUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-[#C5156B] underline hover:text-zinc-900"
              >
                {site.sponsor}
              </a>{" "}
              comes in. They sponsor the project and fine-tuned the Minimax H3
              model into a faster variant called Max. According to the original
              announcement, the fine-tune made inference roughly 50x faster,
              enabling the model to generate video faster than you can watch it.
            </p>
          </section>

          <section className="mt-12">
            <h2 className="text-2xl font-semibold text-zinc-900">Why it is interesting</h2>
            <p className="mt-4 leading-7 text-zinc-700">
              Infinite Slop is a small preview of a much larger shift: media
              that is generated, personalized, and interactive rather than
              pre-produced. A single chat message can send the broadcast in a
              new direction, and the AI's attempt to connect the scenes creates
              unexpected, often funny, moments.
            </p>
            <p className="mt-4 leading-7 text-zinc-700">
              If you want to see the source announcement and the original
              stream, visit{" "}
              <a
                href={site.originPost}
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-[#C5156B] underline hover:text-zinc-900"
              >
                {site.originPostLabel}
              </a>
              . This site is an independent SEO companion that helps more people
              discover the project.
            </p>
          </section>

          <div className="mt-12 flex flex-wrap gap-4">
            <Link
              href="/live"
              className="rounded-full bg-gradient-to-r from-[#8E2DE2] to-[#C5156B] px-6 py-3 font-semibold text-white transition hover:opacity-90"
            >
              Watch the stream
            </Link>
            <a
              href={site.originPost}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-full border border-zinc-200 bg-white px-6 py-3 font-semibold text-zinc-900 shadow-sm transition hover:bg-zinc-50"
            >
              Read the announcement
            </a>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
