import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import { site } from "@/lib/config";

export const metadata: Metadata = {
  title: "How Infinite Slop Works",
  description:
    "How AI turns chat prompts into continuous video, the role of fal.ai and the Max model, and why Infinite Slop can generate faster than real time.",
  alternates: {
    canonical: "/blog/how-infinite-slop-works",
  },
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "How Infinite Slop Works",
  description:
    "How AI turns chat prompts into continuous video, the role of fal.ai and the Max model, and why Infinite Slop can generate faster than real time.",
  author: {
    "@type": "Person",
    name: site.author,
    url: site.authorUrl,
  },
  publisher: {
    "@type": "Organization",
    name: site.name,
    logo: {
      "@type": "ImageObject",
      url: `${site.url}/infinite-slop-logo.png`,
    },
  },
  datePublished: "2026-08-30",
  dateModified: "2026-08-30",
  image: `${site.url}/og-image.png`,
};

export default function HowItWorksPost() {
  return (
    <>
      <Header />
      <main className="flex-1 px-4 py-16 sm:px-6 lg:px-8">
        <article className="mx-auto max-w-3xl">
          <nav className="text-sm text-zinc-500" aria-label="Breadcrumb">
            <Link href="/blog" className="hover:text-zinc-900">
              Blog
            </Link>{" "}
            / <span className="text-zinc-700">How Infinite Slop Works</span>
          </nav>

          <h1 className="mt-6 text-4xl font-semibold tracking-tight text-zinc-900 sm:text-5xl">
            How Infinite Slop Works
          </h1>
          <p className="mt-4 text-lg text-zinc-600">
            Infinite Slop looks like a normal live stream, but the video is not
            pre-recorded. It is generated by AI, guided by the audience, and
            played continuously. Here is the loop that keeps it alive.
          </p>

          <h2 className="mt-12 text-2xl font-semibold text-zinc-900">
            1. A viewer sends a chat message
          </h2>
          <p className="mt-4 leading-7 text-zinc-700">
            The process starts with a simple chat message. It can be a single
            word, a full scene description, a mood, or a random idea. The
            message is treated as a text prompt for the next clip.
          </p>

          <h2 className="mt-12 text-2xl font-semibold text-zinc-900">
            2. AI generates a short clip
          </h2>
          <p className="mt-4 leading-7 text-zinc-700">
            A video generation model receives the prompt and produces a new
            short scene. In Infinite Slop, that model is Max, a fine-tuned
            version of Minimax H3 hosted and accelerated by{" "}
            <a
              href={site.sponsorUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-[#C5156B] underline hover:text-zinc-900"
            >
              {site.sponsor}
            </a>
            . The fine-tune made inference roughly 50x faster, which is why the
            stream can keep up with real-time playback.
          </p>

          <h2 className="mt-12 text-2xl font-semibold text-zinc-900">
            3. The system connects the scene to the story
          </h2>
          <p className="mt-4 leading-7 text-zinc-700">
            The AI does not just produce random clips. It tries to connect each
            new scene to the previous video, so the broadcast feels like one
            continuous sequence rather than a slideshow of disconnected moments.
            The result is a loose, ever-shifting storyline driven by the
            audience.
          </p>

          <h2 className="mt-12 text-2xl font-semibold text-zinc-900">
            4. The loop repeats
          </h2>
          <p className="mt-4 leading-7 text-zinc-700">
            As long as the stream is running, the cycle continues: chat prompt →
            AI generation → story connection → playback. In theory, this loop
            can run forever, producing an infinite stream of AI-generated
            content.
          </p>

          <h2 className="mt-12 text-2xl font-semibold text-zinc-900">
            Why speed is the secret ingredient
          </h2>
          <p className="mt-4 leading-7 text-zinc-700">
            A live stream cannot wait indefinitely. If generation is slower than
            playback, the stream buffers, stutters, or stops. By making the
            model fast enough to generate video faster than it is watched,{" "}
            <a
              href={site.sponsorUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-[#C5156B] underline hover:text-zinc-900"
            >
              {site.sponsor}
            </a>{" "}
            turned a fascinating prototype into a real 24/7 broadcast. The
            original announcement on{" "}
            <a
              href={site.originPost}
              target="_blank"
              rel="noopener noreferrer"
              className="font-medium text-[#C5156B] underline hover:text-zinc-900"
            >
              {site.originPostLabel}
            </a>{" "}
            goes into the details of that speedup.
          </p>

          <p className="mt-8 leading-7 text-zinc-700">
            Ready to see it in action? Head to the{" "}
            <Link
              href="/live"
              className="font-medium text-[#C5156B] underline hover:text-zinc-900"
            >
              live stream
            </Link>{" "}
            and type something in chat.
          </p>
        </article>
      </main>
      <Footer />
      <JsonLd data={articleJsonLd} />
    </>
  );
}
