import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import { site } from "@/lib/config";

export const metadata: Metadata = {
  title: "How Infinite Slop Works",
  description:
    "How AI turns chat prompts into continuous video, the role of fal.ai and the Max model, and why the stream can generate faster than real time.",
  alternates: {
    canonical: "/blog/how-infinite-slop-works",
  },
};

const articleJsonLd = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "How Infinite Slop Works",
  description:
    "How AI turns chat prompts into continuous video, the role of fal.ai and the Max model, and why the stream can generate faster than real time.",
  author: {
    "@type": "Person",
    name: site.author,
    url: site.authorUrl,
  },
  publisher: {
    "@type": "Organization",
    name: site.name,
    logo: {
      "@type": "ImageObject",
      url: `${site.url}/infinite-slop-logo.png`,
    },
  },
  datePublished: "2026-08-30",
  dateModified: "2026-08-30",
  image: `${site.url}/og-image.png`,
};

export default function HowItWorksPost() {
  return (
    <>
      <Header />
      <main className="flex-1 px-4 py-16 sm:px-6 lg:px-8">
        <article className="mx-auto max-w-3xl">
          <nav className="text-sm text-zinc-500" aria-label="Breadcrumb">
            <Link href="/blog" className="hover:text-white">
              Blog
            </Link>{" "}
            / <span className="text-zinc-300">How Infinite Slop Works</span>
          </nav>

          <h1 className="mt-6 text-4xl font-semibold tracking-tight text-white sm:text-5xl">
            How Infinite Slop Works
          </h1>
          <p className="mt-4 text-lg text-zinc-400">
            Infinite Slop looks like a normal live stream, but the video is not
            pre-recorded. It is generated by AI, guided by the audience, and played
            continuously.
          </p>

          <h2 className="mt-12 text-2xl font-semibold text-white">
            1. Chat becomes a prompt
          </h2>
          <p className="text-zinc-300">
            When a viewer sends a message in the chat box, that message is turned
            into a text prompt for a video generation model. The prompt does not
            have to be complex. It can be a single word, a scene description, or a
            random idea.
          </p>

          <h2 className="mt-10 text-2xl font-semibold text-white">
            2. AI generates the next clip
          </h2>
          <p className="text-zinc-300">
            A video generation model takes the prompt and produces a short video
            clip. In the case of Infinite Slop, the model is a fine-tuned version
            of Minimax H3 called Max, hosted and accelerated by{" "}
            <a
              href={site.sponsorUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#C5156B] underline hover:text-white"
            >
              fal.ai
            </a>
            . fal.ai's work made the model roughly 50x faster, which is why the
            stream can generate video faster than it plays.
          </p>

          <h2 className="mt-10 text-2xl font-semibold text-white">
            3. The AI connects the story
          </h2>
          <p className="text-zinc-300">
            The system does not just generate random clips. It attempts to connect
            each new clip to the previous video, so the broadcast feels like one
            continuous sequence. This is what gives Infinite Slop a sense of
            storyline rather than a slideshow of disconnected clips.
          </p>

          <h2 className="mt-10 text-2xl font-semibold text-white">
            4. The loop repeats
          </h2>
          <p className="text-zinc-300">
            As long as the stream is running, the loop continues: chat prompt → AI
            generation → story connection → playback. The result is a broadcast
            that can, in theory, run forever.
          </p>

          <h2 className="mt-10 text-2xl font-semibold text-white">
            Why speed matters
          </h2>
          <p className="text-zinc-300">
            A live stream cannot buffer forever. If generation is slower than
            playback, the stream will stutter or stop. By making the model fast
            enough to generate video faster than real time, fal.ai turned a
            prototype into a real 24/7 broadcast.
          </p>

          <p className="mt-8 text-zinc-300">
            Ready to see it in action? Head to the{" "}
            <Link href="/live" className="text-[#C5156B] underline hover:text-white">
              live stream
            </Link>{" "}
            and type something in chat.
          </p>
        </article>
      </main>
      <Footer />
      <JsonLd data={articleJsonLd} />
    </>
  );
}
